### ISSUE TITLE
Running html_nodes crashes my R

### ISSUE THREAD

**Issue by chuchu89** [tidyverse/rvest#180]
Hello,

When running html_nodes my R crashes, I use the portable versions of R (3.3.2) and RStudio (0.99.903) on this platform:Platform: i386-w64-mingw32/i386 (32-bit).

There is no problem when i run it on a 64bit machine, unfortunately i am bound to use the portable 32 bits versions.  Am a doing something wrong here, or is there a problem and if so is there a work around?

Chuchu

Screenshot error: https://postimg.org/image/axu7s1gf1/

**Comment by Deleetdk** [comment]
It has also been reported on RStudio forum.

https://support.rstudio.com/hc/en-us/community/posts/211201528-Problem-Rstudio-session-aborted-when-using-rvest

**Comment by mosskin-woast** [comment]
I am having this issue with R 3.4.4 on RStudio Server 1.1.442 64-bit.

Here is the code I am running that causes the crash:
`url <- "https://www.cnn.com/2018/07/25/politics/audio-expert-trump-cohen-tape/index.html"
document <- read_html(url)

content_nodes <- c("h1", "h2", "h3", "h4", "h5", "h6", "p", "div", "article", "li")
for(node in content_nodes) {
  print(node)
  print(document %>% html_nodes(node) %>% html_text())
}`

**Comment by hadley** [comment]
That code does not crash my computer, which probably means that it's been fixed in xml2.

If this happens again, please note that this is likely to be an xml2 bug, because the symptoms you describe are of a crash in C code, and rvest contains no C code. If you are still have the problem, I recommend creating a reprex and filing an issue in [xml2](https://github.com/r-lib/xml2)
