### ISSUE TITLE
html_form() does not support valid HTML5 web pages

### ISSUE THREAD

**Issue by ignotus0001** [tidyverse/rvest#192]
I've been running this code successfully for some time (url and security info obfuscated):
```
pgsession <- html_session("https://example.com")
pgform <- html_form(pgsession)[[1]]
filledForm <- set_values(pgform, "userid" = "usr", "password" = "pwd")
submit_form(pgsession, filledForm)
x <-jump_to(pgsession, url)
```
Recently the site upgraded to HTML5, and the call to html_form() failed. I poked around a bit and discovered that the problem occurs in `is_html()` in session.R. The code is checking for Content-Type headers, which of course have been replaced in HTML5 with a `<meta>` tag equivalent, and the function fails. 

Apologies to the maintainers of this wonderful little package, but I'm a bit of a noob with R, and don't feel comfortable putting up a PR. But I would think it shouldn't be too hard to fix.

Addendum:

For those experiencing the same problem who need a workaround until this is fixed, I replaced the call to html_form() above with:

```
formData <- suppressWarnings(xml2::read_xml(httr::content(pgsession$response, "raw"), encoding = "UTF-8", base_url = pgsession$response$url, as_html = TRUE))
pgform <- html_form(formData)[[1]]
```
Seems to work nicely.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
