### ISSUE TITLE
read_html not exported in namespace

### ISSUE THREAD

**Issue by jgilfillan** [tidyverse/rvest#200]
I'm using rvest inside another package, but rvest::read_html() is not working as there is no export in rvest for this function.

**Comment by cderv** [comment]
This subject is also mentionned in #163 , #191. All are duplicates of #109 where it is answered.
`read_html` is a function of `xml2` not `rvest`. When use interactively, a call to `library(rvest)` loads `xml2` too and `read_html` is found. In a package, you have to use `xml2::read_html` directly. it is like `rvest` which calls `xml2::read_html` in its deprecated `rvest::html` function 

Per DESCRIPTION, `rvest` is

>  Wrappers around the 'xml2' and 'httr' packages to make it easy to
    download, then manipulate, HTML and XML

You may consider to depend on those directly rather than on `rvest`.

Interacti
