### ISSUE TITLE
Resolve tidyverse name clashes

### ISSUE THREAD

**Issue by hadley** [tidyverse/rvest#209]
* purrr::pluck
* readr::guess_encoding

**Comment by dmi3kno** [comment]
I presume you want to keep the `purrr` and `readr` function names, since those packages are much more used and more developed. The respective function names in `rvest` need to be deprecated and the new function names need to be proposed instead.

For `pluck` I can think of the following name alternatives:
- [ ] pluck_at()
- [ ] pick()
- [ ] take_out()
- [ ] pull_out()

For `guess_encoding` I propose one of
- [ ] infer_encoding()
- [ ] presume_encoding()
- [ ] deduce_encoding()
- [ ] check_encoding()

I can PR deprecation and new function code, if you pick a name.

**Comment by hadley** [comment]
I think `pluck()` should probably just be deprecated in favour of some alternative in purrr or elsewhere.

For `guess_encoding()`, I think the obvious approach would be to tie it more specifically to HTML, i.e. make it `html_guess_encoding()`.

**Comment by dmi3kno** [comment]
I am all for deprecation, but `rvest::pluck()` is used in the package, so there will have to be an internal alternative, unless you want to introduce dependence on `purrr`, which I would love to avoid.

`html_guess_encoding()` is a great idea. Let me try and PR deprecation code.

**Comment by hadley** [comment]
If it's used internally, we'd leave the function and just not export it. (Which would mean we'd need to give it a new name so we could offer a deprecated version).

**Comment by dmi3kno** [comment]
Yepp, please pick a name for internal function ))

**Comment by hadley** [comment]
`pluck_map()`?

**Comment by beanumber** [comment]
I would love to see `rvest::pluck()` disappear. I run into this particular conflict regularly.
