### ISSUE TITLE
how to get value from each node?

### ISSUE THREAD

**Issue by amjiuzi** [tidyverse/rvest#254]
i want to get author infos from each articles, but some articles may not have author, so it needs a NA to fullfill it.

my scripts bellow seems not working well, so pls help @hadley 

```r
isuUrl <- 'https://digital-library.theiet.org/content/journals/sej/11/6'
read_html(isuUrl) %>% 
  html_nodes(xpath = '//div[@class="articleInToc"]')   %>% 
  lapply(.,function(x){html_node(x,xpath = '//span[@class="meta-value authors"]')%>%html_text()}) %>% 
  unlist()
```

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. In the future please ask it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

But you were pretty close, `html_node()` is vectorized and you need to use `.//`, which starts the search from the current node rather than `//`, which starts the search from the top of the document, e.g.

``` r
isuUrl <- 'https://digital-library.theiet.org/content/journals/sej/11/6'
library(rvest)
#> Loading required package: xml2
page <- xml2::read_html(isuUrl)
articles <- html_nodes(page, xpath = '//div[@class="articleInToc"]')
authors <- html_node(articles, xpath = './/span[@class="meta-value authors"]') %>% html_text()
authors
#> [1] "\nM.D. Harrison\n"                         
#> [2] "\nAnn Blandford\n and \nRichard M. Young\n"
#> [3] "\nAlan Dix\n and \nGregory Abowd\n"        
#> [4] "\nHarold Thimbleby\n and \nPeter Ladkin\n" 
#> [5] "\nC.W. Johnson\n and \nA.J. Telford\n"     
#> [6] "\nJohn McDermid\n"                         
#> [7] NA                                          
#> [8] "\nDavid Ingram\n and \nJean Bacon\n"
```

<sup>Created on 2019-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
