### ISSUE TITLE
why the function "html_nodes()" can't get the "<pre..." tag?

### ISSUE THREAD

**Issue by zhang-jh123** [tidyverse/rvest#381]
In this [links](https://www.ncbi.nlm.nih.gov/nuccore/KU891394.1) from the NCBI website, I can't scrape the text of "[Physeter catodon](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9755)" using rvest packages. Any body Knows?

<img width="831" alt="issues" src="https://github.com/tidyverse/rvest/assets/76564129/fae302bf-352f-44b0-8214-769272e1734a">
<img width="588" alt="results" src="https://github.com/tidyverse/rvest/assets/76564129/e27a32e8-e25c-40f1-b6ed-3b8aead4dd3c">

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
